project_id = "pkgeixqboxsgxbmttuww"

[functions.send-program-application]
verify_jwt = false

[functions.send-referral-signup]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false