// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pkgeixqboxsgxbmttuww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrZ2VpeHFib3hzZ3hibXR0dXd3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjAzNzIsImV4cCI6MjA3MTYzNjM3Mn0.sCZv_KVUkcK7vm5j4yUsyWBQyQ2UR3cvDsOAU60JGYk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});