// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjfvhyrkmqlafxrzponx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZnZoeXJrbXFsYWZ4cnpwb254Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEwMjU5NDYsImV4cCI6MjA4NjYwMTk0Nn0.GtEfuCewJdRT0-fQspT7MjZ6_dqPVqOu03t13OGpyh4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});